# --- Doraemon Melody (frequency, duration divider) ---
melody = [
    (NOTES['A3'], 4), (NOTES['D4'], 8), (NOTES['D4'], 4), (NOTES['FS4'], 8),
    (NOTES['B4'], 4), (NOTES['FS4'], 8), (NOTES['A4'], 4), (REST, 8),
    (NOTES['A4'], 4), (NOTES['B4'], 8), (NOTES['A4'], 4), (NOTES['FS4'], 8),
    (NOTES['G4'], 4), (NOTES['FS4'], 8), (NOTES['E4'], 4), (REST, 8),
    (NOTES['B3'], 4),
    (NOTES['E4'], 8), (NOTES['E4'], 4),
    (NOTES['G4'], 8), (NOTES['CS5'], 4),
    (NOTES['CS5'], 8), (NOTES['B4'], 4),
    (NOTES['A4'], 8),
    (NOTES['G4'], -4),
    (NOTES['G4'], 4),
    (NOTES['FS4'], 8), (NOTES['B3'], 4),
    (NOTES['CS4'], 4), (NOTES['D4'], 4), (NOTES['E4'], 4),

    (REST, 4),

    (NOTES['A3'], 4), (NOTES['D4'], 8), (NOTES['D4'], 4), (NOTES['FS4'], 8),
    (NOTES['B4'], 4), (NOTES['FS4'], 8), (NOTES['A4'], 4), (REST, 8),
    (NOTES['A4'], 4), (NOTES['B4'], 8), (NOTES['A4'], 4), (NOTES['FS4'], 8),
    (NOTES['G4'], 4), (NOTES['FS4'], 8), (NOTES['E4'], 4), (REST, 8),
    (NOTES['B3'], 4),
    (NOTES['E4'], 8), (NOTES['E4'], 4),
    (NOTES['G4'], 8), (NOTES['CS5'], 4),
    (NOTES['CS5'], 8), (NOTES['B4'], 4),
    (NOTES['A4'], 8),
    (NOTES['G4'], -4),
    (NOTES['G4'], 4),
    (NOTES['FS4'], 8), (NOTES['E4'], 8),
    (NOTES['CS4'], 4), (NOTES['E4'], 4), (NOTES['D4'], 4),
    (REST, 4),

    (NOTES['B4'], 4), (REST, 8), (NOTES['B4'], 4), (NOTES['A4'], 8), (NOTES['G4'], 8),
    (NOTES['A4'], 8), (NOTES['B4'], 8), (NOTES['A4'], 8), (REST, 4), (NOTES['E4'], 4),
    (NOTES['FS4'], 8), (NOTES['GS4'], 4), (NOTES['E4'], 8), (NOTES['A4'], 4),
    (REST, 2),

    (NOTES['B4'], 4), (REST, 8),
    (NOTES['A4'], 4), (REST, 8),
    (NOTES['G4'], 4), (REST, 2),
    (NOTES['E4'], 4), (NOTES['E4'], 8), (NOTES['CS5'], 8), (REST, 8),
    (NOTES['B4'], 8), (NOTES['A4'], 8), (REST, 8),
    (NOTES['B4'], 8), (NOTES['A4'], 8), (REST, 8),
    (NOTES['G4'], 8), (REST, -4),

    (NOTES['A4'], 8), (REST, 8), (NOTES['B4'], 8), (NOTES['FS4'], 2),
    (NOTES['E4'], 8), (NOTES['D4'], 2),
]